apiVersion: v2
name: kup6s-pages
description: Kubernetes Operator for multi-tenant static website hosting
type: application
version: 1.0.0-beta.9
appVersion: "1.0.0-beta.9"
home: https://github.com/kup6s/pages
icon: https://pages-docs.kup6s.com/assets/kup6s-pages-icon.svg
sources:
  - https://github.com/kup6s/pages
keywords:
  - kubernetes
  - operator
  - static-sites
  - hosting
  - traefik
maintainers:
  - name: Klein & Partner KG
    url: https://kleinundpartner.at
annotations:
  artifacthub.io/license: EUPL-1.2
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: Basic Install
  artifacthub.io/category: integration-delivery
  artifacthub.io/images: |
    - name: operator
      image: ghcr.io/kup6s/pages-operator
    - name: syncer
      image: ghcr.io/kup6s/pages-syncer
    - name: nginx
      image: docker.io/library/nginx:1.29-alpine
  artifacthub.io/links: |
    - name: Documentation
      url: https://pages-docs.kup6s.com
    - name: Support
      url: https://github.com/kup6s/pages/issues
  artifacthub.io/crds: |
    - kind: StaticSite
      version: v1beta1
      name: staticsites.pages.kup6s.com
      displayName: Static Site
      description: Defines a static website to be hosted on the cluster
