{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kup6s-pages.fullname" . }}-syncer
  labels:
    {{- include "kup6s-pages.syncer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kup6s-pages.fullname" . }}-syncer
subjects:
  - kind: ServiceAccount
    name: {{ include "kup6s-pages.syncer.serviceAccountName" . }}
    namespace: {{ include "kup6s-pages.namespace" . }}
{{- end }}
