{{- if .Values.webhook.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "kup6s-pages.fullname" . }}-webhook
  namespace: {{ include "kup6s-pages.namespace" . }}
  labels:
    {{- include "kup6s-pages.labels" . | nindent 4 }}
  {{- with .Values.webhook.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    {{- toYaml .Values.webhook.entryPoints | nindent 4 }}
  routes:
    - match: Host(`{{ .Values.webhook.domain }}`)
      kind: Rule
      services:
        - name: {{ include "kup6s-pages.fullname" . }}-syncer
          port: {{ .Values.syncer.service.port }}
  tls:
    secretName: {{ include "kup6s-pages.fullname" . }}-webhook-tls
{{- end }}
