{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kup6s-pages.fullname" . }}-operator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kup6s-pages.operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kup6s-pages.fullname" . }}-operator
subjects:
  - kind: ServiceAccount
    name: {{ include "kup6s-pages.operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
